
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 10 2022 14:01:45 MSK (Nov 10 2022 11:01:45 UTC)

// Verification Directory fv/lib_sample 

module lib_sample(CLK, RST_B, SELECT_3, EN_G, BYPASS, CLK_OUT_DIV,
     CLK_OUT_G, CNTR_OUT1, CNTR_OUT2, CNTR_OUT3);
  input CLK, RST_B, SELECT_3, EN_G;
  input [2:0] BYPASS;
  output CLK_OUT_DIV, CLK_OUT_G;
  output [2:0] CNTR_OUT1, CNTR_OUT2, CNTR_OUT3;
  wire CLK, RST_B, SELECT_3, EN_G;
  wire [2:0] BYPASS;
  wire CLK_OUT_DIV, CLK_OUT_G;
  wire [2:0] CNTR_OUT1, CNTR_OUT2, CNTR_OUT3;
  wire n_0, n_1, n_6, n_7, n_8, n_9, n_10, n_11;
  assign CNTR_OUT1[0] = CLK_OUT_DIV;
  F_FD2SQLL \CNTR3_reg[2] (.CD (RST_B), .CP (CLK), .D (n_10), .TI
       (n_11), .TE (CNTR_OUT2[2]), .Q (CNTR_OUT2[2]));
  F_FD1SQLL \CNTR1_reg[2] (.CP (CLK), .D (n_8), .TI (n_9), .TE
       (CNTR_OUT1[2]), .Q (CNTR_OUT1[2]));
  F_FD2QLL \CNTR3_reg[1] (.CD (RST_B), .CP (CLK), .D (n_6), .Q
       (CNTR_OUT2[1]));
  F_FD1QLL \CNTR1_reg[1] (.CP (CLK), .D (n_7), .Q (CNTR_OUT1[1]));
  IVLLX05 g218(.A (n_10), .Z (n_11));
  IVLLX05 g217(.A (n_8), .Z (n_9));
  HA01LL g219__2398(.A (CNTR_OUT1[1]), .B (CLK_OUT_DIV), .S (n_7), .CO
       (n_8));
  HA01LL g220__5107(.A (CNTR_OUT2[1]), .B (CNTR_OUT2[0]), .S (n_6), .CO
       (n_10));
  F_FD2QLL \CNTR3_reg[0] (.CD (RST_B), .CP (CLK), .D (n_1), .Q
       (CNTR_OUT2[0]));
  F_FD1QLL CLK_OUT_DIV_reg(.CP (CLK), .D (n_0), .Q (CLK_OUT_DIV));
  MUX21LL g223__6260(.A (BYPASS[2]), .B (CNTR_OUT2[2]), .S (SELECT_3),
       .Z (CNTR_OUT3[2]));
  MUX21LL g222__4319(.A (BYPASS[1]), .B (CNTR_OUT2[1]), .S (SELECT_3),
       .Z (CNTR_OUT3[1]));
  MUX21LL g221__8428(.A (BYPASS[0]), .B (CNTR_OUT2[0]), .S (SELECT_3),
       .Z (CNTR_OUT3[0]));
  F_AN2LLP g225__5526(.A (CLK_OUT_DIV), .B (EN_G), .Z (CLK_OUT_G));
  IVLLX05 g227(.A (CNTR_OUT2[0]), .Z (n_1));
  IVLLX05 g228(.A (CLK_OUT_DIV), .Z (n_0));
endmodule

