
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 24 2022 13:44:01 MSK (Nov 24 2022 10:44:01 UTC)

// Verification Directory fv/dff 

module dff(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  F_FD1QLL q_reg(.CP (clk), .D (d), .Q (q));
endmodule

