
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 24 2022 13:46:03 MSK (Nov 24 2022 10:46:03 UTC)

// Verification Directory fv/inverter 

module inverter(in, out);
  input in;
  output out;
  wire in;
  wire out;
  IVLLX05 g2(.A (in), .Z (out));
endmodule

